version: '3'

services:

  eval:
    container_name: eval
    image: eval
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
      QT_X11_NO_MITSHM: '1'
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ../src/eval/:/root/src/
      - ../config/eval/:/root/config/
      - ../data/:/root/data/
    command:
    - bash
    - -c
    - | 
        tail -f /dev/null 
